### ISSUE TITLE
'default' is not exported

### ISSUE THREAD

**Issue by rdm** [jakeboone02/numeric-quantity#4]
The code in numeric-quantity works just fine. Under es6, I can reference it like this:

`import numericQuantity from 'numeric-quantity'`

However, when I try to use [rollup](https://www.npmjs.com/package/rollup) on the resulting code, it rejects numeric-quantity with the message:

> [!] Error: 'default' is not exported by node_modules/numeric-quantity/index.js
> https://rollupjs.org/guide/en#error-name-is-not-exported-by-module

**Comment by jakeboone02** [comment]
I think it's because this library is only exposed as a UMD module.  I haven't used rollup, but [this SO answer](https://stackoverflow.com/questions/52068933/can-rollup-plugins-convert-the-majority-of-legacy-libraries-to-es6-modules) may have the solution:  use the [rollup commonjs plugin](https://github.com/rollup/rollup-plugin-commonjs).

**Comment by rdm** [comment]
Well... I tried that, and that works superficially, but it doesn't achieve the purpose, since the net result is that numeric-quantity can't be found after deployment of the stuff I'm working on (which uses storybook and lit-element -- the overall system being something someone else set up...)

I suppose I'm going to have to figure out how to submit a patch that fixes numeric quantity (or maybe I should fork it?)...

**Comment by jakeboone02** [comment]
Oh don't bother forking it.  If you can patch this repo I'll publish the fix ASAP.  In the meantime, I'll investigate creating a ESM version alongside the UMD version.

And just because I'm curious:  how are you using this library?  And how did you find it?

**Comment by jakeboone02** [comment]
I think I figured this out, by using rollup actually.  I'll have a new version published very soon that should cover all the different module systems.

**Comment by jakeboone02** [comment]
OK it's done.  Try v0.4.0.

**Comment by rdm** [comment]
Oh, nice, you're faster than me :)

Also, I'm using it for recipe ingredients -- pretty much following your initial use case, I imagine.

**Comment by jakeboone02** [comment]
Excellent. Thanks!
